<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-08-19 12:13:26                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoArticleCategory_i18n extends AutoProtoArticleCategory_i18n {/*_*/}
?>