<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-10-17 09:54:28                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoCountry extends AutoProtoCountry {/*_*/}
?>