<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-05-01 17:22:37                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoDistrict_i18n extends AutoProtoDistrict_i18n {/*_*/}
?>