<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-02-28 23:08:26                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoFeatureType_i18n extends AutoProtoFeatureType_i18n {/*_*/}
?>