<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-10-17 09:54:28                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoCountry_i18nDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'country_i18n';
		}
		
		public function getObjectName()
		{
			return 'Country_i18n';
		}
		
		public function getSequence()
		{
			return 'country_i18n_id';
		}
	}
?>