<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-10-22 16:42:12                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoRegionDAO extends i18nDAO
	{
		public function getTable()
		{
			return 'region';
		}
		
		public function getObjectName()
		{
			return 'Region';
		}
		
		public function getSequence()
		{
			return 'region_id';
		}
	}
?>