<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-04-11 12:04:28                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoUnitDAO extends i18nDAO
	{
		public function getTable()
		{
			return 'unit';
		}
		
		public function getObjectName()
		{
			return 'Unit';
		}
		
		public function getSequence()
		{
			return 'unit_id';
		}
	}
?>