<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-02-11 11:29:22                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoOfferTypeDAO extends i18nDAO
	{
		public function getTable()
		{
			return 'offer_type';
		}
		
		public function getObjectName()
		{
			return 'OfferType';
		}
		
		public function getSequence()
		{
			return 'offer_type_id';
		}
	}
?>