<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-05-20 11:05:10                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoCustomDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'custom';
		}
		
		public function getObjectName()
		{
			return 'Custom';
		}
		
		public function getSequence()
		{
			return 'custom_id';
		}
	}
?>