<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-05-27 20:06:46                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoStaticPage_i18nDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'static_page_i18n';
		}
		
		public function getObjectName()
		{
			return 'StaticPage_i18n';
		}
		
		public function getSequence()
		{
			return 'static_page_i18n_id';
		}
	}
?>