<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-03-02 10:59:16                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoRealtyType_i18nDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'realty_type_i18n';
		}
		
		public function getObjectName()
		{
			return 'RealtyType_i18n';
		}
		
		public function getSequence()
		{
			return 'realty_type_i18n_id';
		}
	}
?>