<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2013-02-11 12:04:18                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoObjectDAO extends i18nDAO
	{
		public function getTable()
		{
			return 'object';
		}
		
		public function getObjectName()
		{
			return 'Object';
		}
		
		public function getSequence()
		{
			return 'object_id';
		}
	}
?>