<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2013-04-08 14:21:14                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPictureDAO extends StorableDAO
	{
		// no get{Table,ObjectName,Sequence} for abstract class
	}
?>