<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-06-14 11:50:33                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoCity_i18nDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'city_i18n';
		}
		
		public function getObjectName()
		{
			return 'City_i18n';
		}
		
		public function getSequence()
		{
			return 'city_i18n_id';
		}
	}
?>