<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-04-11 10:39:37                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoFeatureType_i18nDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'feature_type_i18n';
		}
		
		public function getObjectName()
		{
			return 'FeatureType_i18n';
		}
		
		public function getSequence()
		{
			return 'feature_type_i18n_id';
		}
	}
?>