<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-05-01 17:22:37                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoDistrictDAO extends i18nDAO
	{
		public function getTable()
		{
			return 'district';
		}
		
		public function getObjectName()
		{
			return 'District';
		}
		
		public function getSequence()
		{
			return 'district_id';
		}
	}
?>