<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2013-04-08 15:20:57                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoArticle_i18nDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'article_i18n';
		}
		
		public function getObjectName()
		{
			return 'Article_i18n';
		}
		
		public function getSequence()
		{
			return 'article_i18n_id';
		}
	}
?>