<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-03-07 20:01:46                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class Autoi18nDAO extends StorableDAO
	{
		// no get{Table,ObjectName,Sequence} for abstract class
	}
?>