<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2013-04-08 14:21:14                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoRealtyPictureDAO extends PictureDAO
	{
		public function getTable()
		{
			return 'realty_picture';
		}
		
		public function getObjectName()
		{
			return 'RealtyPicture';
		}
		
		public function getSequence()
		{
			return 'realty_picture_id';
		}
	}
?>