<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-10-22 16:42:12                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoRegion_i18nDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'region_i18n';
		}
		
		public function getObjectName()
		{
			return 'Region_i18n';
		}
		
		public function getSequence()
		{
			return 'region_i18n_id';
		}
	}
?>