<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2013-04-09 09:46:22                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoNewsPictureDAO extends PictureDAO
	{
		public function getTable()
		{
			return 'news_picture';
		}
		
		public function getObjectName()
		{
			return 'NewsPicture';
		}
		
		public function getSequence()
		{
			return 'news_picture_id';
		}
	}
?>