<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2013-04-09 09:46:22                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoNews_i18nDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'news_i18n';
		}
		
		public function getObjectName()
		{
			return 'News_i18n';
		}
		
		public function getSequence()
		{
			return 'news_i18n_id';
		}
	}
?>