<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-03-02 10:59:16                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoRealtyTypeDAO extends i18nDAO
	{
		public function getTable()
		{
			return 'realty_type';
		}
		
		public function getObjectName()
		{
			return 'RealtyType';
		}
		
		public function getSequence()
		{
			return 'realty_type_id';
		}
	}
?>