<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-03-07 19:12:37                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoTokenDAO extends i18nDAO
	{
		public function getTable()
		{
			return 'token';
		}
		
		public function getObjectName()
		{
			return 'Token';
		}
		
		public function getSequence()
		{
			return 'token_id';
		}
	}
?>