<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-04-11 11:25:37                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoCityDAO extends i18nDAO
	{
		public function getTable()
		{
			return 'city';
		}
		
		public function getObjectName()
		{
			return 'City';
		}
		
		public function getSequence()
		{
			return 'city_id';
		}
	}
?>