<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-08-19 12:13:26                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoArticleCategory_i18nDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'article_category_i18n';
		}
		
		public function getObjectName()
		{
			return 'ArticleCategory_i18n';
		}
		
		public function getSequence()
		{
			return 'article_category_i18n_id';
		}
	}
?>