<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-05-27 20:06:46                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoStaticPageDAO extends i18nDAO
	{
		public function getTable()
		{
			return 'static_page';
		}
		
		public function getObjectName()
		{
			return 'StaticPage';
		}
		
		public function getSequence()
		{
			return 'static_page_id';
		}
	}
?>