<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2013-04-08 15:20:57                     *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class ArticlePicturesDAO extends OneToManyLinked
	{
		public function __construct(Article $article, $lazy = false)
		{
			parent::__construct(
				$article,
				ArticlePicture::dao(),
				$lazy
			);
		}
		
		/**
		 * @return ArticlePicturesDAO
		**/
		public static function create(Article $article, $lazy = false)
		{
			return new self($article, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'object_id';
		}
	}
?>