<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-09-10 16:54:25                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class ArticleSitesDAO extends ManyToManyLinked
	{
		public function __construct(Article $article, $lazy = false)
		{
			parent::__construct(
				$article,
				Realty::dao(),
				$lazy
			);
		}
		
		/**
		 * @return ArticleSitesDAO
		**/
		public static function create(Article $article, $lazy = false)
		{
			return new self($article, $lazy);
		}
		
		public function getHelperTable()
		{
			return 'article_realty';
		}
		
		public function getChildIdField()
		{
			return 'realty_id';
		}
		
		public function getParentIdField()
		{
			return 'article_id';
		}
	}
?>