<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-10-17 09:54:28                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class CountryI18nDAO extends OneToManyLinked
	{
		public function __construct(Country $country, $lazy = false)
		{
			parent::__construct(
				$country,
				Country_i18n::dao(),
				$lazy
			);
		}
		
		/**
		 * @return CountryI18nDAO
		**/
		public static function create(Country $country, $lazy = false)
		{
			return new self($country, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'object_id';
		}
	}
?>