<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-05-20 11:05:10                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class CustomItemsDAO extends OneToManyLinked
	{
		public function __construct(Custom $custom, $lazy = false)
		{
			parent::__construct(
				$custom,
				CustomItem::dao(),
				$lazy
			);
		}
		
		/**
		 * @return CustomItemsDAO
		**/
		public static function create(Custom $custom, $lazy = false)
		{
			return new self($custom, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'parent_id';
		}
	}
?>