<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-05-20 11:05:10                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class CustomDAO extends AutoCustomDAO
	{
		// your brilliant stuff goes here
	}
?>