<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-05-01 17:22:37                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class District_i18nDAO extends AutoDistrict_i18nDAO
	{
		// your brilliant stuff goes here
	}
?>