<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-05-01 19:05:02                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class DistrictI18nDAO extends OneToManyLinked
	{
		public function __construct(District $district, $lazy = false)
		{
			parent::__construct(
				$district,
				District_i18n::dao(),
				$lazy
			);
		}
		
		/**
		 * @return DistrictI18nDAO
		**/
		public static function create(District $district, $lazy = false)
		{
			return new self($district, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'object_id';
		}
	}
?>