<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-02-28 23:08:26                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class FeatureType_i18nDAO extends AutoFeatureType_i18nDAO
	{
		// your brilliant stuff goes here
	}
?>