<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-02-11 11:29:22                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class FeatureTypeDAO extends AutoFeatureTypeDAO
	{
		public function getByGroup(FeatureTypeGroup $group, $isPlain = false)
		{
			$out = array();
			
			try {
				$list = Criteria::create($this)->
					add(
						Expression::eqId('i18n.language', GlobalVar::me()->get('language'))
					)->
					addOrder('i18n.name')->
					getList();

				foreach ($list as $feature) {
					if ($feature->getGroup()->getId() == $group->getId())
						$out[$feature->getId()] = $feature;
				}

				if ($isPlain) {
					$plainList = array();

					foreach ($list as $item) {
						$plainList[$item->getId()] = $item->getName();
					}

					$out = $plainList;
				}
			} catch (Exception $e) {/*_*/}
			
			return $out;
		}
	}
?>
