<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-03-15 13:13:00                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class GroupRulesDAO extends OneToManyLinked
	{
		public function __construct(Group $group, $lazy = false)
		{
			parent::__construct(
				$group,
				GroupAccess::dao(),
				$lazy
			);
		}
		
		/**
		 * @return GroupRulesDAO
		**/
		public static function create(Group $group, $lazy = false)
		{
			return new self($group, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'group_id';
		}
	}
?>