<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-02-11 11:29:22                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	abstract class i18nDAO extends Autoi18nDAO
	{
		const TABLE = 'i18n';
		
		public function getById($id)
		{
			$object = parent::getById($id);
			
			$db = DBPool::me()->getLink();
			$langId = GlobalVar::me()->get('language')->getId();
			
			$result = $db->queryRaw("
				SELECT field, value FROM ".self::TABLE."
				WHERE
					object = '{$this->getObjectName()}'
					AND object_id = $id
					AND language_id = $langId
			");
			
			$propertyList = $object->getProto()->getPropertyList(); // as $name => $property
			
			foreach($result as $row) {
				if (
					!empty($propertyList[$row['field']])
					&& $propertyList[$row['field']]->getType() == 'string'
				)
					$object->{$propertyList[$row['field']]->getSetter()}($row['value']);
			}
			
			return $this->addObjectToMap($object);
		}
	}
?>