<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-02-24 17:15:30                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class LanguageDAO extends AutoLanguageDAO
	{
		private $list = array();
		
		public function getByCode($code = 'en')
		{
			try {
				return $this->getByLogic(Expression::eq('code', $code));
			} catch (DatabaseException $e) {
				if ($code == 'en')
					throw $e;
				else
					return $this->getByCode('en');
			}
		}
		
		public function getList()
		{
			if (empty($this->list)) {
				$list = $this->getPlainList();

				$this->list = array();

				foreach($list as $lang)
					$this->list[$lang->getCode()] = $lang;
			}
			
			return $this->list;
		}
	}
