<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-04-11 10:34:01                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class NewsI18nDAO extends OneToManyLinked
	{
		public function __construct(News $news, $lazy = false)
		{
			parent::__construct(
				$news,
				News_i18n::dao(),
				$lazy
			);
		}
		
		/**
		 * @return NewsI18nDAO
		**/
		public static function create(News $news, $lazy = false)
		{
			return new self($news, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'object_id';
		}
	}
?>