<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2013-04-09 09:46:22                     *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class NewsPicturesDAO extends OneToManyLinked
	{
		public function __construct(News $news, $lazy = false)
		{
			parent::__construct(
				$news,
				ArticlePicture::dao(),
				$lazy
			);
		}
		
		/**
		 * @return NewsPicturesDAO
		**/
		public static function create(News $news, $lazy = false)
		{
			return new self($news, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'news_id';
		}
	}
?>