<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2013-04-09 09:46:22                     *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class News_i18nDAO extends AutoNews_i18nDAO
	{
		// your brilliant stuff goes here
	}
?>