<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-03-15 13:13:00                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class PersonGroupsDAO extends ManyToManyLinked
	{
		public function __construct(Person $person, $lazy = false)
		{
			parent::__construct(
				$person,
				Group::dao(),
				$lazy
			);
		}
		
		/**
		 * @return PersonGroupsDAO
		**/
		public static function create(Person $person, $lazy = false)
		{
			return new self($person, $lazy);
		}
		
		public function getHelperTable()
		{
			return 'person_group';
		}
		
		public function getChildIdField()
		{
			return 'group_id';
		}
		
		public function getParentIdField()
		{
			return 'person_id';
		}
	}
?>