<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-02-11 11:29:22                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class PropertyFeaturesDAO extends ManyToManyLinked
	{
		public function __construct(Property $property, $lazy = false)
		{
			parent::__construct(
				$property,
				Feature::dao(),
				$lazy
			);
		}
		
		/**
		 * @return PropertyFeaturesDAO
		**/
		public static function create(Property $property, $lazy = false)
		{
			return new self($property, $lazy);
		}
		
		public function getHelperTable()
		{
			return 'property_feature';
		}
		
		public function getChildIdField()
		{
			return 'feature_id';
		}
		
		public function getParentIdField()
		{
			return 'property_id';
		}
	}
?>