<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-04-11 10:34:01                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class RealtyTypeI18nDAO extends OneToManyLinked
	{
		public function __construct(RealtyType $realtyType, $lazy = false)
		{
			parent::__construct(
				$realtyType,
				RealtyType_i18n::dao(),
				$lazy
			);
		}
		
		/**
		 * @return RealtyTypeI18nDAO
		**/
		public static function create(RealtyType $realtyType, $lazy = false)
		{
			return new self($realtyType, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'object_id';
		}
	}
?>