<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-03-02 10:59:16                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class RealtyPicturesDAO extends OneToManyLinked
	{
		public function __construct(Realty $realty, $lazy = false)
		{
			parent::__construct(
				$realty,
				RealtyPicture::dao(),
				$lazy
			);
		}
		
		/**
		 * @return RealtyPicturesDAO
		**/
		public static function create(Realty $realty, $lazy = false)
		{
			return new self($realty, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'realty_id';
		}
	}
?>