<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2013-04-08 14:21:14                     *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class RealtyPictureDAO extends AutoRealtyPictureDAO
	{
		public function getSequence()
		{
			return 'picture_id';
		}
	}
