<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-10-22 16:42:12                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class RegionDAO extends AutoRegionDAO
	{
		// your brilliant stuff goes here
	}
?>