<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-10-22 16:40:46                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class RegionI18nDAO extends OneToManyLinked
	{
		public function __construct(Region $region, $lazy = false)
		{
			parent::__construct(
				$region,
				Region_i18n::dao(),
				$lazy
			);
		}
		
		/**
		 * @return RegionI18nDAO
		**/
		public static function create(Region $region, $lazy = false)
		{
			return new self($region, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'object_id';
		}
	}
?>