<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-05-27 20:06:46                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class StaticPage_i18nDAO extends AutoStaticPage_i18nDAO
	{
		// your brilliant stuff goes here
	}
?>