<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-05-27 21:28:10                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class StaticPageI18nDAO extends OneToManyLinked
	{
		public function __construct(StaticPage $staticPage, $lazy = false)
		{
			parent::__construct(
				$staticPage,
				StaticPage_i18n::dao(),
				$lazy
			);
		}
		
		/**
		 * @return StaticPageI18nDAO
		**/
		public static function create(StaticPage $staticPage, $lazy = false)
		{
			return new self($staticPage, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'object_id';
		}
	}
?>