<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-05-27 20:06:46                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class StaticPageDAO extends AutoStaticPageDAO
	{
		private $static = array();

		public function getList(Section $section, $typeId = null)
		{
			if (empty($this->static)) {
				$list = Criteria::create($this)->
					add(
						Expression::andBlock(
							Expression::orBlock(
								Expression::eqId('section', $section),
								Expression::isNull('section')
							)
						)
					)->
					getList();

				foreach ($list as $item) {
					if (empty($this->static[$item->getType()->getId()]))
						$this->static[$item->getType()->getId()] = array();

					$this->static[$item->getType()->getId()][] = $item;
				}
			}

			if (empty($typeId))
				return $this->static;

			return empty($this->static[$typeId])
				? array()
				: $this->static[$typeId];
		}
	}
