<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-04-11 11:19:38                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class TokenI18nDAO extends OneToManyLinked
	{
		public function __construct(Token $token, $lazy = false)
		{
			parent::__construct(
				$token,
				Token_i18n::dao(),
				$lazy
			);
		}
		
		/**
		 * @return TokenI18nDAO
		**/
		public static function create(Token $token, $lazy = false)
		{
			return new self($token, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'object_id';
		}
	}
?>