<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-03-07 19:12:37                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class TokenDAO extends AutoTokenDAO
	{
		public function dropById($id)
		{
			$db = DBPool::me()->getLink()->begin();
			$result = 0;
			
			try {
				$token = $this->getById($id);
				
				if ($token->getObject()) {
					$object = call_user_func(array($token->getObject(), 'dao'))->
						getById($token->getObjectId());
					
					$object->dao()->save($object->setText(null));
				}
				
				$result = parent::dropById($id);
				
				$db->commit();
			} catch (Exception $e) {
				$db->rollback();
			}
			
			return $result;
		}
	}
?>