<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-03-07 19:12:37                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class TokenDAO extends AutoTokenDAO
	{
		// your brilliant stuff goes here
	}
?>