<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-02-24 16:04:39                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class UnitI18nDAO extends OneToManyLinked
	{
		public function __construct(Unit $unit, $lazy = false)
		{
			parent::__construct(
				$unit,
				Unit_i18n::dao(),
				$lazy
			);
		}
		
		/**
		 * @return UnitI18nDAO
		**/
		public static function create(Unit $unit, $lazy = false)
		{
			return new self($unit, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'object_id';
		}
	}
?>