<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-02-24 16:04:39                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class Unit_i18nDAO extends AutoUnit_i18nDAO
	{
		// your brilliant stuff goes here
	}
?>