<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-06-14 11:50:33                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoCity extends Protoi18n
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'City', 8, true, true, false, null, null),
						'i18n' => LightMetaProperty::fill(new LightMetaProperty(), 'i18n', 'i18n_id', 'identifierList', 'City_i18n', null, false, false, false, 2, null),
						'latitude' => LightMetaProperty::fill(new LightMetaProperty(), 'latitude', null, 'float', null, 4, false, true, false, null, null),
						'longitude' => LightMetaProperty::fill(new LightMetaProperty(), 'longitude', null, 'float', null, 4, false, true, false, null, null),
						'region' => LightMetaProperty::fill(new LightMetaProperty(), 'region', 'region_id', 'identifier', 'City', null, false, false, false, 1, 3),
						'prefix' => LightMetaProperty::fill(new LightMetaProperty(), 'prefix', null, 'string', null, 2, false, true, false, null, null)
					)
				);
		}
	}
?>