<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-02-11 11:29:22                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoDictionary extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Dictionary', 8, true, true, false, null, null),
				'token' => LightMetaProperty::fill(new LightMetaProperty(), 'token', null, 'string', null, 16, true, true, false, null, null),
				'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, 16, true, true, false, null, null),
				'value' => LightMetaProperty::fill(new LightMetaProperty(), 'value', null, 'string', null, 16, true, true, false, null, null),
				'lang' => LightMetaProperty::fill(new LightMetaProperty(), 'lang', 'lang_id', 'integerIdentifier', 'Language', null, true, false, false, 1, 3)
			);
		}
	}
?>