<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-03-05 14:51:20                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoFeatureType extends Protoi18n
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'FeatureType', 8, true, true, false, null, null),
						'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, 16, false, true, false, null, null),
						'unit' => LightMetaProperty::fill(new LightMetaProperty(), 'unit', 'unit_id', 'identifier', 'Unit', null, false, false, false, 1, 3),
						'group' => LightMetaProperty::fill(new LightMetaProperty(), 'group', 'group_id', 'enumeration', 'FeatureTypeGroup', null, false, false, false, 1, 3),
						'weight' => LightMetaProperty::fill(new LightMetaProperty(), 'weight', null, 'integer', null, 4, true, true, false, null, null)
					)
				);
		}
	}
?>