<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-10-17 09:54:28                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoCountry extends Protoi18n
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Country', 8, true, true, false, null, null),
						'i18n' => LightMetaProperty::fill(new LightMetaProperty(), 'i18n', 'i18n_id', 'identifierList', 'Country_i18n', null, false, false, false, 2, null),
						'countryCode' => LightMetaProperty::fill(new LightMetaProperty(), 'countryCode', 'country_code', 'string', null, 2, false, true, false, null, null),
						'phoneCode' => LightMetaProperty::fill(new LightMetaProperty(), 'phoneCode', 'phone_code', 'integer', null, 4, false, true, false, null, null)
					)
				);
		}
	}
?>