<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-05-27 21:28:10                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoStaticPage extends Protoi18n
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'StaticPage', 8, true, true, false, null, null),
						'type' => LightMetaProperty::fill(new LightMetaProperty(), 'type', 'type_id', 'enumeration', 'StaticType', null, true, false, false, 1, 3),
						'section' => LightMetaProperty::fill(new LightMetaProperty(), 'section', 'section_id', 'enumeration', 'Section', null, false, false, false, 1, 3),
						'i18n' => LightMetaProperty::fill(new LightMetaProperty(), 'i18n', 'i18n_id', 'identifierList', 'StaticPage_i18n', null, false, false, false, 2, null)
					)
				);
		}
	}
?>