<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-05-27 21:30:29                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoCustom extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Custom', 8, true, true, false, null, null),
				'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, 256, false, true, false, null, null),
				'type' => LightMetaProperty::fill(new LightMetaProperty(), 'type', 'type_id', 'enumeration', 'CustomType', null, true, false, false, 1, 3),
				'section' => LightMetaProperty::fill(new LightMetaProperty(), 'section', 'section_id', 'enumeration', 'Section', null, true, false, false, 1, 3),
				'items' => LightMetaProperty::fill(new LightMetaProperty(), 'items', 'items_id', 'identifierList', 'CustomItem', null, false, false, false, 2, null)
			);
		}
	}
?>