<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2013-03-29 14:16:25                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoPicture extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Picture', 8, true, true, false, null, null),
				'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, 128, true, true, false, null, null),
				'type' => LightMetaProperty::fill(new LightMetaProperty(), 'type', 'type_id', 'enumeration', 'ImageType', null, true, false, false, 1, 3),
				'main' => LightMetaProperty::fill(new LightMetaProperty(), 'main', null, 'boolean', null, null, false, true, false, null, null),
				'size' => LightMetaProperty::fill(new LightMetaProperty(), 'size', null, 'integer', null, 8, false, true, false, null, null),
				'width' => LightMetaProperty::fill(new LightMetaProperty(), 'width', null, 'integer', null, 4, true, true, false, null, null),
				'height' => LightMetaProperty::fill(new LightMetaProperty(), 'height', null, 'integer', null, 4, true, true, false, null, null),
				'realty' => LightMetaProperty::fill(new LightMetaProperty(), 'realty', 'realty_id', 'identifier', 'Realty', null, true, false, false, 1, 3)
			);
		}
	}
?>