<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2013-04-08 14:21:14                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoRealtyPicture extends ProtoPicture
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'realty' => LightMetaProperty::fill(new LightMetaProperty(), 'realty', 'realty_id', 'identifier', 'Realty', null, true, false, false, 1, 3),
						'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'RealtyPicture', 8, true, true, false, null, null)
					)
				);
		}
	}
?>