<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-02-11 11:29:22                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoFeature extends ProtoObject
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Feature', 8, true, true, false, null, null),
						'type' => LightMetaProperty::fill(new LightMetaProperty(), 'type', 'type_id', 'identifier', 'FeatureType', null, true, false, false, 1, 3),
						'value' => LightMetaProperty::fill(new LightMetaProperty(), 'value', null, 'string', null, 16, true, true, false, null, null),
						'weight' => LightMetaProperty::fill(new LightMetaProperty(), 'weight', null, 'integer', null, 4, false, true, false, null, null)
					)
				);
		}
	}
?>