<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-05-01 17:37:09                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoPerson extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Person', 8, true, true, false, null, null),
				'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, 16, true, true, false, null, null),
				'surname' => LightMetaProperty::fill(new LightMetaProperty(), 'surname', null, 'string', null, 16, false, true, false, null, null),
				'email' => LightMetaProperty::fill(new LightMetaProperty(), 'email', null, 'string', null, 32, true, true, false, null, null),
				'status' => LightMetaProperty::fill(new LightMetaProperty(), 'status', 'status_id', 'enumeration', 'PersonStatus', null, true, false, false, 1, null),
				'created' => LightMetaProperty::fill(new LightMetaProperty(), 'created', null, 'timestamp', 'Timestamp', null, true, true, false, null, null),
				'username' => LightMetaProperty::fill(new LightMetaProperty(), 'username', null, 'string', null, 16, true, true, false, null, null),
				'password' => LightMetaProperty::fill(new LightMetaProperty(), 'password', null, 'string', null, 40, true, true, false, null, null),
				'autologin' => LightMetaProperty::fill(new LightMetaProperty(), 'autologin', null, 'string', null, 40, false, true, false, null, null),
				'groups' => LightMetaProperty::fill(new LightMetaProperty(), 'groups', 'group_id', 'identifierList', 'Group', null, false, false, false, 3, null)
			);
		}
	}
?>