<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-02-11 11:29:22                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoFeatureType extends ProtoObject
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'FeatureType', 8, true, true, false, null, null),
						'unit' => LightMetaProperty::fill(new LightMetaProperty(), 'unit', 'unit_id', 'identifier', 'Unit', null, true, false, false, 1, null)
					)
				);
		}
	}
?>