<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-11-04 14:27:59                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoCustomItem extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'CustomItem', 8, true, true, false, null, null),
				'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, 256, false, true, false, null, null),
				'order' => LightMetaProperty::fill(new LightMetaProperty(), 'order', null, 'integer', null, 4, false, true, false, null, null),
				'parent' => LightMetaProperty::fill(new LightMetaProperty(), 'parent', 'parent_id', 'identifier', 'Custom', null, true, false, false, 1, 3),
				'realty' => LightMetaProperty::fill(new LightMetaProperty(), 'realty', 'realty_id', 'identifier', 'Realty', null, false, false, false, 1, 3),
				'article' => LightMetaProperty::fill(new LightMetaProperty(), 'article', 'article_id', 'identifier', 'Article', null, false, false, false, 1, 3)
			);
		}
	}
?>