<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-10-21 16:27:04                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoUnit extends Protoi18n
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Unit', 8, true, true, false, null, null),
						'i18n' => LightMetaProperty::fill(new LightMetaProperty(), 'i18n', 'i18n_id', 'identifierList', 'Unit_i18n', null, false, false, false, 2, null),
						'sign' => LightMetaProperty::fill(new LightMetaProperty(), 'sign', null, 'string', null, 16, false, true, false, null, null),
						'type' => LightMetaProperty::fill(new LightMetaProperty(), 'type', null, 'integer', null, 4, true, true, false, null, null)
					)
				);
		}
	}
?>