<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-03-18 23:17:16                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoGroupAccess extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'GroupAccess', 8, true, true, false, null, null),
				'group' => LightMetaProperty::fill(new LightMetaProperty(), 'group', 'group_id', 'identifier', 'Group', null, true, false, false, 1, 3),
				'resource' => LightMetaProperty::fill(new LightMetaProperty(), 'resource', 'resource_id', 'identifier', 'Resource', null, true, false, false, 1, 3),
				'access' => LightMetaProperty::fill(new LightMetaProperty(), 'access', null, 'integer', null, 4, true, true, false, null, null)
			);
		}
	}
?>