<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2013-02-11 12:04:18                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoObject extends Protoi18n
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Object', 8, true, true, false, null, null),
						'created' => LightMetaProperty::fill(new LightMetaProperty(), 'created', null, 'timestamp', 'Timestamp', null, true, true, false, null, null),
						'published' => LightMetaProperty::fill(new LightMetaProperty(), 'published', null, 'timestamp', 'Timestamp', null, false, true, false, null, null),
						'type' => LightMetaProperty::fill(new LightMetaProperty(), 'type', 'type_id', 'identifier', 'PropertyType', null, true, false, false, 1, 3),
						'offer' => LightMetaProperty::fill(new LightMetaProperty(), 'offer', 'offer_id', 'identifier', 'OfferType', null, true, false, false, 1, 3),
						'agent' => LightMetaProperty::fill(new LightMetaProperty(), 'agent', 'agent_id', 'identifier', 'Agent', null, false, false, false, 1, 3),
						'owner' => LightMetaProperty::fill(new LightMetaProperty(), 'owner', 'owner_id', 'identifier', 'Owner', null, false, false, false, 1, 3)
					)
				);
		}
	}
?>