<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-02-11 11:29:22                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoProperty extends Protoi18n
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Property', 8, true, true, false, null, null),
						'object' => LightMetaProperty::fill(new LightMetaProperty(), 'object', 'object_id', 'identifier', 'Object', null, true, false, false, 1, 3),
						'lang' => LightMetaProperty::fill(new LightMetaProperty(), 'lang', 'lang_id', 'integerIdentifier', 'Language', null, true, false, false, 1, 3),
						'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, 128, true, true, false, null, null),
						'content' => LightMetaProperty::fill(new LightMetaProperty(), 'content', null, 'string', null, 4096, false, true, false, null, null),
						'features' => LightMetaProperty::fill(new LightMetaProperty(), 'features', 'feature_id', 'identifierList', 'Feature', null, true, false, false, 3, null)
					)
				);
		}
	}
?>