<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-05-01 19:08:34                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoDistrict extends i18n
	{
		protected $i18n = null;
		protected $latitude = null;
		protected $longitude = null;
		protected $city = null;
		protected $cityId = null;
		
		/**
		 * @return DistrictI18nDAO
		**/
		public function getI18n($lazy = false)
		{
			if (!$this->i18n || ($this->i18n->isLazy() != $lazy)) {
				$this->i18n = new DistrictI18nDAO($this, $lazy);
			}
			
			return $this->i18n;
		}
		
		/**
		 * @return District
		**/
		public function fillI18n($collection, $lazy = false)
		{
			$this->i18n = new DistrictI18nDAO($this, $lazy);
			
			if (!$this->id) {
				throw new WrongStateException(
					'i do not know which object i belong to'
				);
			}
			
			$this->i18n->mergeList($collection);
			
			return $this;
		}
		
		public function getLatitude()
		{
			return $this->latitude;
		}
		
		/**
		 * @return District
		**/
		public function setLatitude($latitude)
		{
			$this->latitude = $latitude;
			
			return $this;
		}
		
		public function getLongitude()
		{
			return $this->longitude;
		}
		
		/**
		 * @return District
		**/
		public function setLongitude($longitude)
		{
			$this->longitude = $longitude;
			
			return $this;
		}
		
		/**
		 * @return City
		**/
		public function getCity()
		{
			if (!$this->city && $this->cityId) {
				$this->city = City::dao()->getById($this->cityId);
			}
			
			return $this->city;
		}
		
		public function getCityId()
		{
			return $this->city
				? $this->city->getId()
				: $this->cityId;
		}
		
		/**
		 * @return District
		**/
		public function setCity(City $city = null)
		{
			$this->city = $city;
			$this->cityId = $city ? $city->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return District
		**/
		public function setCityId($id = null)
		{
			$this->city = null;
			$this->cityId = $id;
			
			return $this;
		}
		
		/**
		 * @return District
		**/
		public function dropCity()
		{
			$this->city = null;
			$this->cityId = null;
			
			return $this;
		}
	}
?>