<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-03-01 00:27:34                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoFeatureType extends i18n
	{
		protected $name = null;
		protected $unit = null;
		protected $unitId = null;
		protected $group = null;
		protected $groupId = null;
		protected $weight = 1;
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return FeatureType
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
		
		/**
		 * @return Unit
		**/
		public function getUnit()
		{
			if (!$this->unit && $this->unitId) {
				$this->unit = Unit::dao()->getById($this->unitId);
			}
			
			return $this->unit;
		}
		
		public function getUnitId()
		{
			return $this->unit
				? $this->unit->getId()
				: $this->unitId;
		}
		
		/**
		 * @return FeatureType
		**/
		public function setUnit(Unit $unit = null)
		{
			$this->unit = $unit;
			$this->unitId = $unit ? $unit->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return FeatureType
		**/
		public function setUnitId($id = null)
		{
			$this->unit = null;
			$this->unitId = $id;
			
			return $this;
		}
		
		/**
		 * @return FeatureType
		**/
		public function dropUnit()
		{
			$this->unit = null;
			$this->unitId = null;
			
			return $this;
		}
		
		/**
		 * @return FeatureTypeGroup
		**/
		public function getGroup()
		{
			if (!$this->group && $this->groupId) {
				$this->group = new FeatureTypeGroup($this->groupId);
			}
			
			return $this->group;
		}
		
		public function getGroupId()
		{
			return $this->group
				? $this->group->getId()
				: $this->groupId;
		}
		
		/**
		 * @return FeatureType
		**/
		public function setGroup(FeatureTypeGroup $group = null)
		{
			$this->group = $group;
			$this->groupId = $group ? $group->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return FeatureType
		**/
		public function setGroupId($id = null)
		{
			$this->group = null;
			$this->groupId = $id;
			
			return $this;
		}
		
		/**
		 * @return FeatureType
		**/
		public function dropGroup()
		{
			$this->group = null;
			$this->groupId = null;
			
			return $this;
		}
		
		public function getWeight()
		{
			return $this->weight;
		}
		
		/**
		 * @return FeatureType
		**/
		public function setWeight($weight)
		{
			$this->weight = $weight;
			
			return $this;
		}
	}
?>