<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-06-14 11:50:33                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoRealtyType extends i18n
	{
		protected $prefix = null;
		protected $i18n = null;
		
		public function getPrefix()
		{
			return $this->prefix;
		}
		
		/**
		 * @return RealtyType
		**/
		public function setPrefix($prefix)
		{
			$this->prefix = $prefix;
			
			return $this;
		}
		
		/**
		 * @return RealtyTypeI18nDAO
		**/
		public function getI18n($lazy = false)
		{
			if (!$this->i18n || ($this->i18n->isLazy() != $lazy)) {
				$this->i18n = new RealtyTypeI18nDAO($this, $lazy);
			}
			
			return $this->i18n;
		}
		
		/**
		 * @return RealtyType
		**/
		public function fillI18n($collection, $lazy = false)
		{
			$this->i18n = new RealtyTypeI18nDAO($this, $lazy);
			
			if (!$this->id) {
				throw new WrongStateException(
					'i do not know which object i belong to'
				);
			}
			
			$this->i18n->mergeList($collection);
			
			return $this;
		}
	}
?>