<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-11-04 14:27:59                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoCustomItem extends IdentifiableObject
	{
		protected $name = null;
		protected $order = null;
		protected $parent = null;
		protected $parentId = null;
		protected $realty = null;
		protected $realtyId = null;
		protected $article = null;
		protected $articleId = null;
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return CustomItem
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
		
		public function getOrder()
		{
			return $this->order;
		}
		
		/**
		 * @return CustomItem
		**/
		public function setOrder($order)
		{
			$this->order = $order;
			
			return $this;
		}
		
		/**
		 * @return Custom
		**/
		public function getParent()
		{
			if (!$this->parent && $this->parentId) {
				$this->parent = Custom::dao()->getById($this->parentId);
			}
			
			return $this->parent;
		}
		
		public function getParentId()
		{
			return $this->parent
				? $this->parent->getId()
				: $this->parentId;
		}
		
		/**
		 * @return CustomItem
		**/
		public function setParent(Custom $parent)
		{
			$this->parent = $parent;
			$this->parentId = $parent ? $parent->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return CustomItem
		**/
		public function setParentId($id)
		{
			$this->parent = null;
			$this->parentId = $id;
			
			return $this;
		}
		
		/**
		 * @return CustomItem
		**/
		public function dropParent()
		{
			$this->parent = null;
			$this->parentId = null;
			
			return $this;
		}
		
		/**
		 * @return Realty
		**/
		public function getRealty()
		{
			if (!$this->realty && $this->realtyId) {
				$this->realty = Realty::dao()->getById($this->realtyId);
			}
			
			return $this->realty;
		}
		
		public function getRealtyId()
		{
			return $this->realty
				? $this->realty->getId()
				: $this->realtyId;
		}
		
		/**
		 * @return CustomItem
		**/
		public function setRealty(Realty $realty = null)
		{
			$this->realty = $realty;
			$this->realtyId = $realty ? $realty->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return CustomItem
		**/
		public function setRealtyId($id = null)
		{
			$this->realty = null;
			$this->realtyId = $id;
			
			return $this;
		}
		
		/**
		 * @return CustomItem
		**/
		public function dropRealty()
		{
			$this->realty = null;
			$this->realtyId = null;
			
			return $this;
		}
		
		/**
		 * @return Article
		**/
		public function getArticle()
		{
			if (!$this->article && $this->articleId) {
				$this->article = Article::dao()->getById($this->articleId);
			}
			
			return $this->article;
		}
		
		public function getArticleId()
		{
			return $this->article
				? $this->article->getId()
				: $this->articleId;
		}
		
		/**
		 * @return CustomItem
		**/
		public function setArticle(Article $article = null)
		{
			$this->article = $article;
			$this->articleId = $article ? $article->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return CustomItem
		**/
		public function setArticleId($id = null)
		{
			$this->article = null;
			$this->articleId = $id;
			
			return $this;
		}
		
		/**
		 * @return CustomItem
		**/
		public function dropArticle()
		{
			$this->article = null;
			$this->articleId = null;
			
			return $this;
		}
	}
?>