<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-02-11 11:29:22                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoFeatureType extends Object
	{
		protected $unit = null;
		
		/**
		 * @return Unit
		**/
		public function getUnit()
		{
			return $this->unit;
		}
		
		/**
		 * @return FeatureType
		**/
		public function setUnit(Unit $unit)
		{
			$this->unit = $unit;
			
			return $this;
		}
		
		/**
		 * @return FeatureType
		**/
		public function dropUnit()
		{
			$this->unit = null;
			
			return $this;
		}
	}
?>