<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-02-11 11:29:22                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class Autoi18n extends IdentifiableObject
	{
		protected $lang = null;
		protected $langId = null;
		
		/**
		 * @return Language
		**/
		public function getLang()
		{
			if (!$this->lang && $this->langId) {
				$this->lang = Language::dao()->getById($this->langId);
			}
			
			return $this->lang;
		}
		
		public function getLangId()
		{
			return $this->lang
				? $this->lang->getId()
				: $this->langId;
		}
		
		/**
		 * @return i18n
		**/
		public function setLang(Language $lang)
		{
			$this->lang = $lang;
			$this->langId = $lang ? $lang->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return i18n
		**/
		public function setLangId($id)
		{
			$this->lang = null;
			$this->langId = $id;
			
			return $this;
		}
		
		/**
		 * @return i18n
		**/
		public function dropLang()
		{
			$this->lang = null;
			$this->langId = null;
			
			return $this;
		}
	}
?>