<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-03-18 23:17:16                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoGroupAccess extends IdentifiableObject
	{
		protected $group = null;
		protected $groupId = null;
		protected $resource = null;
		protected $resourceId = null;
		protected $access = 0;
		
		/**
		 * @return Group
		**/
		public function getGroup()
		{
			if (!$this->group && $this->groupId) {
				$this->group = Group::dao()->getById($this->groupId);
			}
			
			return $this->group;
		}
		
		public function getGroupId()
		{
			return $this->group
				? $this->group->getId()
				: $this->groupId;
		}
		
		/**
		 * @return GroupAccess
		**/
		public function setGroup(Group $group)
		{
			$this->group = $group;
			$this->groupId = $group ? $group->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return GroupAccess
		**/
		public function setGroupId($id)
		{
			$this->group = null;
			$this->groupId = $id;
			
			return $this;
		}
		
		/**
		 * @return GroupAccess
		**/
		public function dropGroup()
		{
			$this->group = null;
			$this->groupId = null;
			
			return $this;
		}
		
		/**
		 * @return Resource
		**/
		public function getResource()
		{
			if (!$this->resource && $this->resourceId) {
				$this->resource = Resource::dao()->getById($this->resourceId);
			}
			
			return $this->resource;
		}
		
		public function getResourceId()
		{
			return $this->resource
				? $this->resource->getId()
				: $this->resourceId;
		}
		
		/**
		 * @return GroupAccess
		**/
		public function setResource(Resource $resource)
		{
			$this->resource = $resource;
			$this->resourceId = $resource ? $resource->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return GroupAccess
		**/
		public function setResourceId($id)
		{
			$this->resource = null;
			$this->resourceId = $id;
			
			return $this;
		}
		
		/**
		 * @return GroupAccess
		**/
		public function dropResource()
		{
			$this->resource = null;
			$this->resourceId = null;
			
			return $this;
		}
		
		public function getAccess()
		{
			return $this->access;
		}
		
		/**
		 * @return GroupAccess
		**/
		public function setAccess($access)
		{
			$this->access = $access;
			
			return $this;
		}
	}
?>