<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-05-20 11:48:13                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoCustom extends IdentifiableObject
	{
		protected $name = null;
		protected $type = null;
		protected $typeId = null;
		protected $section = null;
		protected $sectionId = null;
		protected $items = null;
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return Custom
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
		
		/**
		 * @return CustomType
		**/
		public function getType()
		{
			if (!$this->type && $this->typeId) {
				$this->type = new CustomType($this->typeId);
			}
			
			return $this->type;
		}
		
		public function getTypeId()
		{
			return $this->type
				? $this->type->getId()
				: $this->typeId;
		}
		
		/**
		 * @return Custom
		**/
		public function setType(CustomType $type)
		{
			$this->type = $type;
			$this->typeId = $type ? $type->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return Custom
		**/
		public function setTypeId($id)
		{
			$this->type = null;
			$this->typeId = $id;
			
			return $this;
		}
		
		/**
		 * @return Custom
		**/
		public function dropType()
		{
			$this->type = null;
			$this->typeId = null;
			
			return $this;
		}
		
		/**
		 * @return Section
		**/
		public function getSection()
		{
			if (!$this->section && $this->sectionId) {
				$this->section = new Section($this->sectionId);
			}
			
			return $this->section;
		}
		
		public function getSectionId()
		{
			return $this->section
				? $this->section->getId()
				: $this->sectionId;
		}
		
		/**
		 * @return Custom
		**/
		public function setSection(Section $section)
		{
			$this->section = $section;
			$this->sectionId = $section ? $section->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return Custom
		**/
		public function setSectionId($id)
		{
			$this->section = null;
			$this->sectionId = $id;
			
			return $this;
		}
		
		/**
		 * @return Custom
		**/
		public function dropSection()
		{
			$this->section = null;
			$this->sectionId = null;
			
			return $this;
		}
		
		/**
		 * @return CustomItemsDAO
		**/
		public function getItems($lazy = false)
		{
			if (!$this->items || ($this->items->isLazy() != $lazy)) {
				$this->items = new CustomItemsDAO($this, $lazy);
			}
			
			return $this->items;
		}
		
		/**
		 * @return Custom
		**/
		public function fillItems($collection, $lazy = false)
		{
			$this->items = new CustomItemsDAO($this, $lazy);
			
			if (!$this->id) {
				throw new WrongStateException(
					'i do not know which object i belong to'
				);
			}
			
			$this->items->mergeList($collection);
			
			return $this;
		}
	}
?>