<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-03-02 10:59:16                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoRealtyType extends i18n
	{
		protected $name = null;
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return RealtyType
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
	}
?>