<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-05-01 17:22:37                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoDistrict extends i18n
	{
		protected $name = null;
		protected $latitude = null;
		protected $longitude = null;
		protected $city = null;
		protected $cityId = null;
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return District
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
		
		public function getLatitude()
		{
			return $this->latitude;
		}
		
		/**
		 * @return District
		**/
		public function setLatitude($latitude)
		{
			$this->latitude = $latitude;
			
			return $this;
		}
		
		public function getLongitude()
		{
			return $this->longitude;
		}
		
		/**
		 * @return District
		**/
		public function setLongitude($longitude)
		{
			$this->longitude = $longitude;
			
			return $this;
		}
		
		/**
		 * @return City
		**/
		public function getCity()
		{
			if (!$this->city && $this->cityId) {
				$this->city = City::dao()->getById($this->cityId);
			}
			
			return $this->city;
		}
		
		public function getCityId()
		{
			return $this->city
				? $this->city->getId()
				: $this->cityId;
		}
		
		/**
		 * @return District
		**/
		public function setCity(City $city = null)
		{
			$this->city = $city;
			$this->cityId = $city ? $city->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return District
		**/
		public function setCityId($id = null)
		{
			$this->city = null;
			$this->cityId = $id;
			
			return $this;
		}
		
		/**
		 * @return District
		**/
		public function dropCity()
		{
			$this->city = null;
			$this->cityId = null;
			
			return $this;
		}
	}
?>