<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-10-22 16:42:12                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoRegion extends i18n
	{
		protected $i18n = null;
		protected $latitude = null;
		protected $longitude = null;
		protected $country = null;
		protected $countryId = null;
		
		/**
		 * @return RegionI18nDAO
		**/
		public function getI18n($lazy = false)
		{
			if (!$this->i18n || ($this->i18n->isLazy() != $lazy)) {
				$this->i18n = new RegionI18nDAO($this, $lazy);
			}
			
			return $this->i18n;
		}
		
		/**
		 * @return Region
		**/
		public function fillI18n($collection, $lazy = false)
		{
			$this->i18n = new RegionI18nDAO($this, $lazy);
			
			if (!$this->id) {
				throw new WrongStateException(
					'i do not know which object i belong to'
				);
			}
			
			$this->i18n->mergeList($collection);
			
			return $this;
		}
		
		public function getLatitude()
		{
			return $this->latitude;
		}
		
		/**
		 * @return Region
		**/
		public function setLatitude($latitude)
		{
			$this->latitude = $latitude;
			
			return $this;
		}
		
		public function getLongitude()
		{
			return $this->longitude;
		}
		
		/**
		 * @return Region
		**/
		public function setLongitude($longitude)
		{
			$this->longitude = $longitude;
			
			return $this;
		}
		
		/**
		 * @return Country
		**/
		public function getCountry()
		{
			if (!$this->country && $this->countryId) {
				$this->country = Country::dao()->getById($this->countryId);
			}
			
			return $this->country;
		}
		
		public function getCountryId()
		{
			return $this->country
				? $this->country->getId()
				: $this->countryId;
		}
		
		/**
		 * @return Region
		**/
		public function setCountry(Country $country)
		{
			$this->country = $country;
			$this->countryId = $country ? $country->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return Region
		**/
		public function setCountryId($id)
		{
			$this->country = null;
			$this->countryId = $id;
			
			return $this;
		}
		
		/**
		 * @return Region
		**/
		public function dropCountry()
		{
			$this->country = null;
			$this->countryId = null;
			
			return $this;
		}
	}
?>