<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-02-11 11:29:22                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoCompany extends i18n
	{
		protected $name = null;
		protected $phone = null;
		protected $email = null;
		protected $created = null;
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return Company
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
		
		public function getPhone()
		{
			return $this->phone;
		}
		
		/**
		 * @return Company
		**/
		public function setPhone($phone)
		{
			$this->phone = $phone;
			
			return $this;
		}
		
		public function getEmail()
		{
			return $this->email;
		}
		
		/**
		 * @return Company
		**/
		public function setEmail($email)
		{
			$this->email = $email;
			
			return $this;
		}
		
		/**
		 * @return Timestamp
		**/
		public function getCreated()
		{
			return $this->created;
		}
		
		/**
		 * @return Company
		**/
		public function setCreated(Timestamp $created)
		{
			$this->created = $created;
			
			return $this;
		}
		
		/**
		 * @return Company
		**/
		public function dropCreated()
		{
			$this->created = null;
			
			return $this;
		}
	}
?>