<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-03-07 19:12:37                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoToken extends i18n
	{
		protected $name = null;
		protected $value = null;
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return Token
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
		
		public function getValue()
		{
			return $this->value;
		}
		
		/**
		 * @return Token
		**/
		public function setValue($value)
		{
			$this->value = $value;
			
			return $this;
		}
	}
?>