<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-02-11 11:29:22                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoFeature extends Object
	{
		protected $value = null;
		protected $weight = null;
		
		public function getValue()
		{
			return $this->value;
		}
		
		/**
		 * @return Feature
		**/
		public function setValue($value)
		{
			$this->value = $value;
			
			return $this;
		}
		
		public function getWeight()
		{
			return $this->weight;
		}
		
		/**
		 * @return Feature
		**/
		public function setWeight($weight)
		{
			$this->weight = $weight;
			
			return $this;
		}
	}
?>