<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2013-04-08 14:21:14                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoRealtyPicture extends Picture
	{
		protected $realty = null;
		protected $realtyId = null;
		
		/**
		 * @return Realty
		**/
		public function getRealty()
		{
			if (!$this->realty && $this->realtyId) {
				$this->realty = Realty::dao()->getById($this->realtyId);
			}
			
			return $this->realty;
		}
		
		public function getRealtyId()
		{
			return $this->realty
				? $this->realty->getId()
				: $this->realtyId;
		}
		
		/**
		 * @return RealtyPicture
		**/
		public function setRealty(Realty $realty)
		{
			$this->realty = $realty;
			$this->realtyId = $realty ? $realty->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return RealtyPicture
		**/
		public function setRealtyId($id)
		{
			$this->realty = null;
			$this->realtyId = $id;
			
			return $this;
		}
		
		/**
		 * @return RealtyPicture
		**/
		public function dropRealty()
		{
			$this->realty = null;
			$this->realtyId = null;
			
			return $this;
		}
	}
?>