<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-02-11 11:29:22                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoOwner extends Person
	{
		protected $proved = null;
		protected $code = null;
		protected $autoLogin = null;
		
		public function getProved()
		{
			return $this->proved;
		}
		
		public function isProved()
		{
			return $this->proved;
		}
		
		/**
		 * @return Owner
		**/
		public function setProved($proved = false)
		{
			$this->proved = ($proved === true);
			
			return $this;
		}
		
		public function getCode()
		{
			return $this->code;
		}
		
		/**
		 * @return Owner
		**/
		public function setCode($code)
		{
			$this->code = $code;
			
			return $this;
		}
		
		public function getAutoLogin()
		{
			return $this->autoLogin;
		}
		
		/**
		 * @return Owner
		**/
		public function setAutoLogin($autoLogin)
		{
			$this->autoLogin = $autoLogin;
			
			return $this;
		}
	}
?>