<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-02-24 17:22:44                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoUnit extends i18n
	{
		protected $name = null;
		protected $sign = null;
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return Unit
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
		
		public function getSign()
		{
			return $this->sign;
		}
		
		/**
		 * @return Unit
		**/
		public function setSign($sign)
		{
			$this->sign = $sign;
			
			return $this;
		}
	}
?>