<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-04-11 10:39:37                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoGroup extends IdentifiableObject
	{
		protected $name = null;
		protected $text = null;
		protected $rules = null;
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return Group
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
		
		public function getText()
		{
			return $this->text;
		}
		
		/**
		 * @return Group
		**/
		public function setText($text)
		{
			$this->text = $text;
			
			return $this;
		}
		
		/**
		 * @return GroupRulesDAO
		**/
		public function getRules($lazy = false)
		{
			if (!$this->rules || ($this->rules->isLazy() != $lazy)) {
				$this->rules = new GroupRulesDAO($this, $lazy);
			}
			
			return $this->rules;
		}
		
		/**
		 * @return Group
		**/
		public function fillRules($collection, $lazy = false)
		{
			$this->rules = new GroupRulesDAO($this, $lazy);
			
			if (!$this->id) {
				throw new WrongStateException(
					'i do not know which object i belong to'
				);
			}
			
			$this->rules->mergeList($collection);
			
			return $this;
		}
	}
?>