<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-03-02 10:59:16                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoFeature extends IdentifiableObject
	{
		protected $type = null;
		protected $typeId = null;
		protected $value = null;
		protected $realty = null;
		protected $realtyId = null;
		
		/**
		 * @return FeatureType
		**/
		public function getType()
		{
			if (!$this->type && $this->typeId) {
				$this->type = FeatureType::dao()->getById($this->typeId);
			}
			
			return $this->type;
		}
		
		public function getTypeId()
		{
			return $this->type
				? $this->type->getId()
				: $this->typeId;
		}
		
		/**
		 * @return Feature
		**/
		public function setType(FeatureType $type)
		{
			$this->type = $type;
			$this->typeId = $type ? $type->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return Feature
		**/
		public function setTypeId($id)
		{
			$this->type = null;
			$this->typeId = $id;
			
			return $this;
		}
		
		/**
		 * @return Feature
		**/
		public function dropType()
		{
			$this->type = null;
			$this->typeId = null;
			
			return $this;
		}
		
		public function getValue()
		{
			return $this->value;
		}
		
		/**
		 * @return Feature
		**/
		public function setValue($value)
		{
			$this->value = $value;
			
			return $this;
		}
		
		/**
		 * @return Realty
		**/
		public function getRealty()
		{
			if (!$this->realty && $this->realtyId) {
				$this->realty = Realty::dao()->getById($this->realtyId);
			}
			
			return $this->realty;
		}
		
		public function getRealtyId()
		{
			return $this->realty
				? $this->realty->getId()
				: $this->realtyId;
		}
		
		/**
		 * @return Feature
		**/
		public function setRealty(Realty $realty)
		{
			$this->realty = $realty;
			$this->realtyId = $realty ? $realty->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return Feature
		**/
		public function setRealtyId($id)
		{
			$this->realty = null;
			$this->realtyId = $id;
			
			return $this;
		}
		
		/**
		 * @return Feature
		**/
		public function dropRealty()
		{
			$this->realty = null;
			$this->realtyId = null;
			
			return $this;
		}
	}
?>