<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-03-02 10:59:16                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoCity extends i18n
	{
		protected $name = null;
		protected $latitude = null;
		protected $longitude = null;
		protected $region = null;
		protected $regionId = null;
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return City
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
		
		public function getLatitude()
		{
			return $this->latitude;
		}
		
		/**
		 * @return City
		**/
		public function setLatitude($latitude)
		{
			$this->latitude = $latitude;
			
			return $this;
		}
		
		public function getLongitude()
		{
			return $this->longitude;
		}
		
		/**
		 * @return City
		**/
		public function setLongitude($longitude)
		{
			$this->longitude = $longitude;
			
			return $this;
		}
		
		/**
		 * @return City
		**/
		public function getRegion()
		{
			if (!$this->region && $this->regionId) {
				$this->region = City::dao()->getById($this->regionId);
			}
			
			return $this->region;
		}
		
		public function getRegionId()
		{
			return $this->region
				? $this->region->getId()
				: $this->regionId;
		}
		
		/**
		 * @return City
		**/
		public function setRegion(City $region = null)
		{
			$this->region = $region;
			$this->regionId = $region ? $region->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return City
		**/
		public function setRegionId($id = null)
		{
			$this->region = null;
			$this->regionId = $id;
			
			return $this;
		}
		
		/**
		 * @return City
		**/
		public function dropRegion()
		{
			$this->region = null;
			$this->regionId = null;
			
			return $this;
		}
	}
?>