<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-03-02 10:59:16                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class Acl extends Singleton
	{
		private $user = null;
		private $groups = array();
		private $rules = array();

		public static function me()
		{
			parent::getInstance(__CLASS__);
		}

		public function setUser(Person $user)
		{
			$this->user = $user;
		}

		public function getAccessListByUser(Person $user)
		{
			$list = Criteria::create(Person::dao())->
				setProjection(
					Projection::chain()->
					add(
						Projection::property('groups.rules.resource')
					)->
					add(
						Projection::property('groups.rules.access')
					)
				)->
				add(
					Expression::eqId('id', $user)
				);

			$list->toString();

//				getCustomList();
			
//			foreach ($user->getGroups()->getList() as $group) {
//				$group->getRules()->getList();
//			}
		}
	}
?>