<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-08-19 12:13:26                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ArticleCategory extends AutoArticleCategory implements Prototyped, DAOConnected
	{
		/**
		 * @return ArticleCategory
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return ArticleCategoryDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('ArticleCategoryDAO');
		}
		
		/**
		 * @return ProtoArticleCategory
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoArticleCategory');
		}
		
		public function getWebSlug()
		{
			return $this->getSlug()
				? $this->getSlug()
				: $this->getId();
		}
		
		public function getIconUrl()
		{
			return null;
		}
	}
		
?>