<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-10-25 13:39:10                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ArticleType extends Enumeration
	{
		const INFO		= 1;
		const PROJECT	= 2;
		const ABOUT		= 3;
		
		protected $names = array(
			self::INFO		=> '_S__INFO___',
			self::PROJECT	=> '_S__PROJECT___',
			self::ABOUT		=> '_S__ABOUT___',
		);
		
		/**
		 * @return ArticleType
		 */
		public static function information()
		{
			return new self(self::INFO);
		}
		
		/**
		 * @return ArticleType
		 */
		public static function project()
		{
			return new self(self::PROJECT);
		}
		
		/**
		 * @return ArticleType
		 */
		public static function about()
		{
			return new self(self::ABOUT);
		}
	}
