<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2013-04-08 15:20:57                     *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class Article extends AutoArticle implements Prototyped, DAOConnected
	{
		/**
		 * @return Article
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return ArticleDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('ArticleDAO');
		}
		
		/**
		 * @return ProtoArticle
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoArticle');
		}
		
		public function getPreview()
		{
			$list = $this->getPictures()->getList();

			return reset($list);
		}
	}
?>