<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2013-04-08 15:20:57                     *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class Article_i18n extends AutoArticle_i18n implements Prototyped, DAOConnected
	{
		/**
		 * @return Article_i18n
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return Article_i18nDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('Article_i18nDAO');
		}
		
		/**
		 * @return ProtoArticle_i18n
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoArticle_i18n');
		}
		
		// your brilliant stuff goes here
	}
?>