<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-03-02 10:59:16                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class City extends AutoCity implements Prototyped, DAOConnected
	{
		/**
		 * @return City
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return CityDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('CityDAO');
		}
		
		/**
		 * @return ProtoCity
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoCity');
		}
		
		// your brilliant stuff goes here
	}
?>