<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-05-20 11:05:10                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class Custom extends AutoCustom implements Prototyped, DAOConnected
	{
		/**
		 * @return Custom
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return CustomDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('CustomDAO');
		}
		
		/**
		 * @return ProtoCustom
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoCustom');
		}
		
		// your brilliant stuff goes here
		/**
		 * @return CustomItemsDAO
		**/
		public function getItems($lazy = false)
		{
			return parent::getItems($lazy)->
				setCriteria(Criteria::create()->addOrder('order'));
		}
	}
