<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-05-20 11:05:10                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class CustomItem extends AutoCustomItem implements Prototyped, DAOConnected
	{
		/**
		 * @return CustomItem
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return CustomItemDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('CustomItemDAO');
		}
		
		/**
		 * @return ProtoCustomItem
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoCustomItem');
		}
		
		// your brilliant stuff goes here
	}
?>