<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-05-20 11:05:10                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class CustomType extends Enumeration
	{
		const CAROUSEL	= 1;

		protected $names = array(
			self::CAROUSEL	=> 'carousel',
		);

		/**
		 * @return CustomType
		 */
		public static function carousel()
		{
			return new self(self::CAROUSEL);
		}
	}
?>