<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-05-01 17:22:37                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class District extends AutoDistrict implements Prototyped, DAOConnected
	{
		/**
		 * @return District
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return DistrictDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('DistrictDAO');
		}
		
		/**
		 * @return ProtoDistrict
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoDistrict');
		}
		
		// your brilliant stuff goes here
	}
?>