<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-05-01 17:22:37                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class District_i18n extends AutoDistrict_i18n implements Prototyped, DAOConnected
	{
		/**
		 * @return District_i18n
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return District_i18nDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('District_i18nDAO');
		}
		
		/**
		 * @return ProtoDistrict_i18n
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoDistrict_i18n');
		}
		
		// your brilliant stuff goes here
	}
?>