<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-02-28 23:22:25                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class FeatureTypeGroup extends Enumeration
	{
		const INDOOR		= 1;
		const OUTDOOR	= 2;
		const GENERAL	= 3;

		protected $names = array(
			self::INDOOR	=> '_S__INDOOR___',
			self::OUTDOOR	=> '_S__OUTDOOR___',
			self::GENERAL	=> '_S__GENEREAL___',
		);
		
		public static function create()
		{
			return new self(parent::getAnyId());
		}
		
		/**
		 * @return FeatureTypeGroup
		 */
		public static function getAnyObject()
		{
			return new self(self::getAnyId());
		}
		
		public static function indoor()
		{
			return new self(FeatureTypeGroup::INDOOR);
		}
		
		public static function outdoor()
		{
			return new self(FeatureTypeGroup::OUTDOOR);
		}
		
		public static function general()
		{
			return new self(FeatureTypeGroup::GENERAL);
		}
	}
?>