<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-02-11 11:29:22                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class FeatureType extends AutoFeatureType implements Prototyped, DAOConnected
	{
		/**
		 * @return FeatureType
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return FeatureTypeDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('FeatureTypeDAO');
		}
		
		/**
		 * @return ProtoFeatureType
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoFeatureType');
		}
		
		// Some very important features from the COMMON group (SYNC with DB)
		const PRICE			= 1;
		const AREA			= 2;
		const BEDROOMS		= 3;
		const TOILETS		= 4;
		const PARKING_LOTS	= 5;
		const PRICE_MONTHLY	= 6;	// for rent (future)
		const PRICE_DAYLY	= 7;
		
		const VAT			= 77;
		
		public function getSign()
		{
			return $this->getUnit()
				? $this->getUnit()->getSign()
				: null;
		}
		
		public function getPriceTypes()
		{
			return array(
				self::PRICE,
				self::PRICE_MONTHLY,
				self::PRICE_DAYLY,
			);
		}
	}
