<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-02-11 11:29:22                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class Feature extends AutoFeature implements Prototyped, DAOConnected
	{
		/**
		 * @return Feature
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return FeatureDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('FeatureDAO');
		}
		
		/**
		 * @return ProtoFeature
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoFeature');
		}
		
		// your brilliant stuff goes here
	}
?>