<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-02-28 23:22:25                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class FeatureTypeGroup extends Enumeration
	{
		const INDOOR	= 1;
		const OUTDOOR	= 2;
			
		protected $names = array(
			self::INDOOR	=> 'Indoor options',
			self::OUTDOOR	=> 'Outdoor options',
		);
		
		protected $native = array(
			'ru'	=> array(
				self::INDOOR	=> 'Внутридомовые опции',
				self::OUTDOOR	=> 'Наружные опции',
			),
			'el'	=> array(
				self::INDOOR	=> 'Indoor',
				self::OUTDOOR	=> 'Outdoor',
			),
		);
		
		public static function create()
		{
			return new self(parent::getAnyId());
		}

		/**
		 * @return FeatureTypeGroup
		 */
		public static function getAnyObject()
		{
			return new self(self::getAnyId());
		}
		
		public function setId($id)
		{
			$this->native['en'] = $this->names;
			return parent::setId($id);
		}

		public function getNameList()
		{
			$lang = GlobalVar::me()->has('language')
				? GlobalVar::me()->get('language')->getCode()
				: 'en';
				
			return isset($this->native[$lang])
				? $this->native[$lang]
				: $this->native['en'];
		}
	}
?>