<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-02-28 23:08:26                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class FeatureType_i18n extends AutoFeatureType_i18n implements Prototyped, DAOConnected
	{
		/**
		 * @return FeatureType_i18n
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return FeatureType_i18nDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('FeatureType_i18nDAO');
		}
		
		/**
		 * @return ProtoFeatureType_i18n
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoFeatureType_i18n');
		}
		
		// your brilliant stuff goes here
	}
?>