<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-02-11 11:29:22                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class GlobalVar extends Singleton
	{
		private $vars = array();

		/**
		 * @return GlobalVar
		 */
		public static function me()
		{
			return parent::getInstance(__CLASS__);
		}
		
		public function set($first, $second = null)
		{
			if (is_array($first)) {
				$this->vars = array_merge(
					$this->vars,
					$first
				);
			} else {
				$this->vars[$first] = $second;
			}
			
			return $this;
		}
		
		public function get($name)
		{
			Assert::isIndexExists($this->vars, $name);
			
			return $this->vars[$name];
		}
		
		public function has($name)
		{
			return array_key_exists($name, $this->vars);
		}
		
		public function getList()
		{
			return $this->vars;
		}

		public function import($vendor)
		{
			$path = PATH_VENDORS.$vendor;

			if (!file_exists($path))
				throw new MissingElementException('Vendor does not exist '.$vendor);

			if (class_exists('AutoloaderPool')) {
				AutoloaderPool::get('onPHP')->addPath($path);
			} else {
				set_include_path(get_include_path().PS.$path);
			}
			
			return $this;
		}
	}