<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-02-11 11:29:22                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	abstract class i18n extends Autoi18n implements Prototyped
	{
		/**
		 * @return i18n
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return Protoi18n
		**/
		public static function proto()
		{
			return Singleton::getInstance('Protoi18n');
		}
		
		// your brilliant stuff goes here
	}
?>