<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2013-04-09 09:46:22                     *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class NewsPicture extends AutoNewsPicture implements Prototyped, DAOConnected
	{
		/**
		 * @return NewsPicture
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return NewsPictureDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('NewsPictureDAO');
		}
		
		/**
		 * @return ProtoNewsPicture
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoNewsPicture');
		}
		
		// your brilliant stuff goes here
	}
?>