<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-02-11 11:29:22                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class OfferType extends AutoOfferType implements Prototyped, DAOConnected
	{
		/**
		 * @return OfferType
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return OfferTypeDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('OfferTypeDAO');
		}
		
		/**
		 * @return ProtoOfferType
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoOfferType');
		}
		
		// your brilliant stuff goes here
	}
?>