<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-03-02 10:59:16                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class OfferType extends Enumeration
	{
		const BUY	= 1;
		const RENT	= 2;
		
		protected $names = array(
			self::BUY	=> '_S__BUY___',
			self::RENT	=> '_S__RENT___',
		);
		
		public static function create()
		{
			return new self(parent::getAnyId());
		}

		/**
		 * @return FeatureTypeGroup
		 */
		public static function buy()
		{
			return new self(self::BUY);
		}
		
		/**
		 * @return FeatureTypeGroup
		 */
		public static function rent()
		{
			return new self(self::RENT);
		}
	}
