<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-03-02 10:59:16                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class OfferType extends Enumeration
	{
		const SALE	= 1;
		const RENT	= 2;
		
		protected $names = array(
			self::SALE	=> 'sale',
			self::RENT	=> 'rent',
		);
	}
