<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-02-11 11:29:22                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class Owner extends AutoOwner implements Prototyped, DAOConnected
	{
		/**
		 * @return Owner
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return OwnerDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('OwnerDAO');
		}
		
		/**
		 * @return ProtoOwner
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoOwner');
		}
		
		// your brilliant stuff goes here
	}
?>