<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-03-02 10:59:16                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class Picture extends AutoPicture implements Prototyped, DAOConnected
	{
		/**
		 * @return Picture
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return PictureDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('PictureDAO');
		}
		
		/**
		 * @return ProtoPicture
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoPicture');
		}
		
		// your brilliant stuff goes here
	}
?>