<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-03-02 10:59:16                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class Picture extends AutoPicture implements Prototyped, DAOConnected
	{
		/**
		 * @return Picture
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return PictureDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('PictureDAO');
		}
		
		/**
		 * @return ProtoPicture
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoPicture');
		}
		
		private $uploadName = null;

		/**
		 * @param string $name
		 * @return Picture
		 */
		public function setUploadName($name)
		{
			$this->uploadName = $name;
			return $this;
		}

		public function getUploadName()
		{
			return $this->uploadName;
		}

		public function getUrl()
		{
			return PATH_WEB_PIX
				.$this->getId().'.'.$this->getType()->getExtension();
		}

		public function getPath()
		{
			return PATH_PIX
				.implode(DS, str_split(sprintf('%08d.', $this->getId()), 2)).DS
				.$this->getId().'.'.$this->getType()->getExtension();
		}
	}
?>