<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-02-11 11:29:22                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PropertyType extends AutoPropertyType implements Prototyped, DAOConnected
	{
		/**
		 * @return PropertyType
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return PropertyTypeDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('PropertyTypeDAO');
		}
		
		/**
		 * @return ProtoPropertyType
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoPropertyType');
		}
		
		// your brilliant stuff goes here
	}
?>