<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-03-02 10:59:16                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class RealtyType extends AutoRealtyType implements Prototyped, DAOConnected
	{
		/**
		 * @return RealtyType
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return RealtyTypeDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('RealtyTypeDAO');
		}
		
		/**
		 * @return ProtoRealtyType
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoRealtyType');
		}
		
		// your brilliant stuff goes here
	}
?>