<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-03-02 10:59:16                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class Realty extends AutoRealty implements Prototyped, DAOConnected
	{
		/**
		 * @return Realty
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return RealtyDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('RealtyDAO');
		}
		
		/**
		 * @return ProtoRealty
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoRealty');
		}

		/**
		 * Feature list indexed by FeatureType ids
		 * @return type
		 */
		public function getFeatureList()
		{
			$list = parent::getFeatures(false);
			
			$out = array();
			foreach ($list as $item) {
				$out[$item->getType()->getId()] = $item;
			}
			
			return $out;
		}
	}
?>