<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-03-02 10:59:16                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class Realty extends AutoRealty implements Prototyped, DAOConnected
	{
		private $featureList = array();
		
		/**
		 * @return Realty
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return RealtyDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('RealtyDAO');
		}
		
		/**
		 * @return ProtoRealty
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoRealty');
		}

		/**
		 * Feature list indexed by FeatureType ids
		 * @return type
		 */
		public function getFeatureList()
		{
			if (empty($this->featureList)) {
				$list = $this->getFeatures();

				$this->featureList = array();
				foreach ($list as $item) {
					$this->featureList[$item->getType()->getId()] = $item;
				}
			}
			
			return $this->featureList;
		}
		
		public function getFeaturesByGroup(FeatureTypeGroup $group)
		{
			$list = $this->getFeatureList();
			$types = FeatureType::dao()->getByGroup($group);
			
			return array_intersect_key($list, $types);
		}
	}
?>