<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-10-22 16:42:12                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class Region_i18n extends AutoRegion_i18n implements Prototyped, DAOConnected
	{
		/**
		 * @return Region_i18n
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return Region_i18nDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('Region_i18nDAO');
		}
		
		/**
		 * @return ProtoRegion_i18n
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoRegion_i18n');
		}
		
		// your brilliant stuff goes here
	}
?>