<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-03-15 13:13:00                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ResourceType extends Enumeration
	{
		const OBJECT	= 1;

		protected $names = array(
			self::OBJECT	=> 'object'
		);

		public static function object()
		{
			return new self(self::OBJECT);
		}
	}
?>