<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-05-20 11:48:13                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class Section extends Enumeration
	{
		const BUY	= 1;
		const RENT	= 2;

		protected $names = array(
			self::BUY	=> '___buy___',
			self::RENT	=> '___rent___',
		);

		protected $slugs = array(
			self::BUY	=> 'buy',
			self::RENT	=> 'rent',
		);


		public static function create($id)
		{
			return new self($id);
		}
		
		/**
		 * @return Section
		 */
		public static function buy()
		{
			return new self(self::BUY);
		}
		/**
		 * @return Section
		 */
		public static function rent()
		{
			return new self(self::RENT);
		}

		public function getSlug()
		{
			return $this->slugs[$this->id];
		}
	}
