<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-05-27 20:06:46                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class StaticPage extends AutoStaticPage implements Prototyped, DAOConnected
	{
		/**
		 * @return StaticPage
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return StaticPageDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('StaticPageDAO');
		}
		
		/**
		 * @return ProtoStaticPage
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoStaticPage');
		}
		
		// your brilliant stuff goes here
	}
?>