<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-05-27 20:06:46                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class StaticPage_i18n extends AutoStaticPage_i18n implements Prototyped, DAOConnected
	{
		/**
		 * @return StaticPage_i18n
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return StaticPage_i18nDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('StaticPage_i18nDAO');
		}
		
		/**
		 * @return ProtoStaticPage_i18n
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoStaticPage_i18n');
		}
		
		// your brilliant stuff goes here
	}
?>