<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-05-27 20:06:46                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class StaticType extends Enumeration
	{
		const ABOUT		= 1;
		const CONTACT	= 2;
		const TWITTER	= 3;
		const LEGAL		= 4;
		const PHONE		= 5;
		const EMAIL		= 6;
		const ADDRESS	= 7;
		const COMPANY	= 8;

		protected $names = array(
			self::ABOUT		=> 'about',
			self::CONTACT	=> 'contact',
			self::TWITTER	=> 'twitter',
			self::LEGAL		=> 'legal',
			self::PHONE		=> 'phone',
			self::EMAIL		=> 'email',
			self::ADDRESS	=> 'address',
			self::COMPANY	=> 'company',
		);

		/**
		 * @return StaticType
		 */
		public static function about()
		{
			return new self(self::ABOUT);
		}
	}
