<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-03-07 19:12:37                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class Token_i18n extends AutoToken_i18n implements Prototyped, DAOConnected
	{
		/**
		 * @return Token_i18n
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return Token_i18nDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('Token_i18nDAO');
		}
		
		/**
		 * @return ProtoToken_i18n
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoToken_i18n');
		}
		
		// your brilliant stuff goes here
	}
?>