<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2013-03-07 20:01:46                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class Unit extends AutoUnit implements Prototyped, DAOConnected
	{
		const TYPE_BOOL		= 1;
		const TYPE_INT		= 2;
		const TYPE_TEXT		= 3;
		const TYPE_DATE		= 4;
		const TYPE_MONEY	= 5;
		
		private $names = array(
			self::TYPE_BOOL		=>	'boolean',
			self::TYPE_INT		=>	'integer',
			self::TYPE_TEXT		=>	'text',
			self::TYPE_DATE		=>	'date',
			self::TYPE_MONEY	=>	'money',
		);
		
		/**
		 * @return Unit
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return UnitDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('UnitDAO');
		}
		
		/**
		 * @return ProtoUnit
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoUnit');
		}
		
		public function getTypeList()
		{
			return $this->names;
		}
		
		public function getTypeName()
		{
			return $this->type
				? $this->names[$this->type]
				: null;
		}
	}
